
service: awesome-api-v2

provider:
  name: aws
  runtime: nodejs12.x

# you can overwrite defaults here
  stage: dev
  region: ap-southeast-2

  environment:
    GOOGLE_MAPS_API_KEY: googlemapskey1234


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: first-endpoint
          method: GET
      - http:
          path: second-endpoint
          method: POST

  envVariable:
    handler: envVariable.trial
    events:
      - http:
          path: envVariable-endpoint
          method: GET
    environment:
      OTHER_API_KEY: otherapikey1234
    


# you can add CloudFormation resource templates here
resources:
  Resources:
    uploadBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-jinguploads

    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-jing-users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: orderId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1        
  
          # Outputs:
  #    NewOutput:
  #      Description: "Description for the output"
  #      Value: "Some output value"
